
    export const PRO_ADMIN = ['CAN_ACCESS_MY_TEAM', 'CAN_ACCESS_ACCOUNT_ACTIVITY',
    'CAN_EDIT_ADMIN_ACCOUNT', 'CAN_ACCESS_BUSINESS_ACCOUNT', 'CAN_ACCESS_ADMIN_ACCOUNT', 'CAN_ACCESS_BILLING_INFORMATION'];

   export const PRO_USER = ['CAN_ACCESS_ADMIN_ACCOUNT'];